# this taskfile should run as the non-privileged user
---
- name: install pyenv
  git: repo="https://github.com/pyenv/pyenv.git"
       dest="{{ common.user_home }}/.pyenv"
       version="v1.1.4"

- name: insert/update pyenv block in .bashrc
  blockinfile:
    dest: "{{ common.user_home }}/.bashrc"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
      fi
      source $PYENV_ROOT/completions/pyenv.bash
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"

- name: install python
  shell: source $HOME/.bashrc && pyenv install {{ common.python_version }}
  args:
    creates: "{{ common.user_home }}/.pyenv/versions/{{ common.python_version}}/bin/python"

- name: install pyenv-virtualenvwrapper
  git: repo="https://github.com/pyenv/pyenv-virtualenvwrapper.git"
       dest="{{ common.user_home }}/.pyenv/plugins/pyenv-virtualenvwrapper"
       version="v20140609"
