# this taskfile should run as the non-privileged user
---
- name: install pyenv
  git: repo="https://github.com/pyenv/pyenv.git"
       dest="{{ common.user_home }}/.pyenv"
       version="{{ pyenv.version }}"

- name: set 'shell_init_file' to .bashrc
  set_fact:
    shell_init_file: .bashrc
  when: ansible_os_family == "RedHat"

- name: set 'shell_init_file' to .profile
  set_fact:
    shell_init_file: .profile
  when: ansible_os_family == "Debian"

- name: insert/update pyenv block in {{ shell_init_file }}
  blockinfile:
    dest: "{{ common.user_home }}/{{ shell_init_file }}"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
      fi
      source $PYENV_ROOT/completions/pyenv.bash
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"

- name: install python
  shell: source {{ common.user_home }}/{{ shell_init_file }} && pyenv install {{ common.python_version }}
  args:
    executable: /bin/bash
    creates: "{{ common.user_home }}/.pyenv/versions/{{ common.python_version}}/bin/python"

- name: install pyenv-virtualenvwrapper
  git: repo="https://github.com/pyenv/pyenv-virtualenvwrapper.git"
       dest="{{ common.user_home }}/.pyenv/plugins/pyenv-virtualenvwrapper"
       version="{{ pyenv.virtualenvwrapper_plugin_version }}"
