---
- include_tasks: install_packages_redhat.yml
  when: ansible_os_family == "RedHat"
- include_tasks: install_packages_debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: setup_user.yml

- import_tasks: install_python.yml
  become: yes
  become_method: su
  become_user: "{{ common.create_user }}"
